export const publicPaymentCopy = {
  confirmation: {
    acceptedStatus: 'Paiement accepté',
    acceptedTitle: "Le plan est en cours d'activation sur votre espace.",
    acceptedBodyLead: 'Votre paiement a été validé.',
    acceptedBodyTail:
      "Vous pouvez retourner dans le produit et poursuivre l'onboarding ou reprendre votre travail là où vous l'avez laissé.",
    acceptedSteps: [
      'Vérifier votre tableau de bord',
      "Relancer l'atelier premium voulu",
      'Contrôler le plan actif dans la page tarifaire',
    ],
    pendingStatus: 'Paiement en cours de confirmation',
    pendingTitle: "La transaction est revenue, mais l'activation n'est pas encore finalisée.",
    pendingBody:
      'Le prestataire de paiement traite encore la confirmation finale. Ce cas est normal quand la redirection revient plus vite que la mise à jour interne.',
    pendingSteps: [
      'Rafraîchir cette page dans quelques secondes',
      'Vérifier ensuite la page tarifaire',
      "Revenir au tableau de bord si l'activation apparaît",
    ],
    refusedStatus: 'Paiement refusé',
    refusedTitle: "La transaction n'a pas été validée.",
    refusedBody:
      "Aucun abonnement n'est activé pour le moment. Vous pouvez relancer un essai depuis la page tarifaire ou revenir sur une offre existante.",
    refusedSteps: [
      'Vérifier les informations de paiement',
      'Relancer la souscription depuis la page tarifaire',
      'Contacter le support si le refus se répète',
    ],
    errorStatus: 'Erreur de paiement',
    errorTitle: 'Le retour du paiement est incomplet ou contradictoire.',
    errorBody:
      'La redirection a bien atteint la plateforme, mais le statut final reste incohérent. Mieux vaut vérifier avant toute nouvelle tentative.',
    errorSteps: [
      'Recharger cette page une fois',
      'Vérifier la page tarifaire',
      'Contacter le support avec la référence de commande',
    ],
    unknownStatus: 'Vérification en cours',
    unknownTitle: 'Le retour est bien reçu, mais le statut définitif n’est pas encore exposé.',
    unknownBody:
      'Si vous avez déjà réglé la transaction, il suffit souvent de rafraîchir puis de vérifier votre espace quelques secondes plus tard.',
    unknownSteps: [
      'Rafraîchir cette page',
      'Vérifier la page tarifaire',
      'Se connecter puis contrôler le tableau de bord',
    ],
    header: {
      badge: 'Retour paiement ClicToPay',
      title: 'Paiement confirmé',
      body:
        'La transaction est revenue sur la plateforme. Cet écran vous dit immédiatement si le plan premium est actif, en attente, ou s’il faut relancer proprement.',
    },
    statusLabel: 'Statut',
    referenceLabel: 'Référence',
    missingReference: 'Non transmise',
    publicApiLabel: 'API publique',
    apiAvailable: 'Disponible',
    apiUnavailable: 'Aucune référence',
    reviewEyebrow: 'Lecture du retour',
    stepPrefix: 'Étape',
    actionsEyebrow: 'Actions utiles',
    dashboardCta: 'Vérifier votre tableau de bord',
    pricingCta: 'Retour à la page tarifaire',
    refreshStatus: 'Rafraîchir le statut',
    loginCta: 'Se connecter',
    techTraceEyebrow: 'Trace technique',
    orderReferenceTitle: 'Référence de commande',
    missingUrlReference: "Aucune référence transmise dans l'URL.",
    verificationEndpointTitle: 'Endpoint de vérification',
    nextEyebrow: 'Ce qui suit',
    nextSteps: [
      'Le tableau de bord et la page tarifaire restent la source de vérité côté produit.',
      'En cas de statut en attente, la situation se débloque en général sans nouvelle action bancaire.',
      'Si le statut reste incohérent, conservez la référence et passez par le support.',
    ],
  },
  refusal: {
    refusedStatus: 'Paiement refusé',
    transactionRejected: "La transaction n'a pas été validée.",
    subscriptionNotActivated: "L'abonnement n'a pas été activé.",
    verifyPaymentMethod: 'Vérifier la carte ou le moyen de paiement utilisé.',
    retryCta: 'Réessayer',
    returnHome: "Retour à l'accueil",
    referenceLabel: 'Référence',
    missingReference: 'Non transmise',
    header: {
      title: 'Paiement non abouti',
      body:
        "Aucun accès premium n'est activé pour le moment, mais vous pouvez reprendre proprement depuis les offres ou vérifier la référence de retour.",
    },
    statusLabel: 'Statut',
    amountLabel: 'Montant',
    noConfirmedDebit: 'Aucun débit confirmé',
    reviewEyebrow: 'Lecture du retour',
    body:
      "Le prestataire a renvoyé un refus ou un échec de transaction. Tant que le statut final n'est pas accepté, la plateforme reste sur le plan actuel.",
    steps: [
      'Vérifier la carte ou le moyen de paiement utilisé.',
      'Revenir sur la page tarifaire pour relancer une tentative propre.',
      'Contacter le support si la référence bloque à plusieurs reprises.',
    ],
    stepPrefix: 'Étape',
    actionsEyebrow: 'Actions utiles',
    loginCta: 'Se connecter',
    referenceEyebrow: 'Référence de retour',
    transmittedReferenceTitle: 'Référence transmise',
    noReferenceBody: "Aucune référence n'a été transmise dans l'URL de retour.",
    reassuranceEyebrow: 'Réassurance',
    reassuranceBody:
      "Aucun montant n'a été débité tant que la transaction n'est pas acceptée. En cas de doute, la page tarifaire et votre espace connecté restent les deux écrans de vérification utiles.",
    loading: 'Chargement…',
  },
} as const;
