export const studentOralCopy = {
  sttFailure: 'La transcription vocale a échoué.',
  providerPrefix: 'Fournisseur :',
  capabilityLimited: 'Fonction momentanément limitée.',
  followUpError: "Impossible de générer une relance d'examinateur.",
  dialogTitle: "Simulation dialoguée avec l'examinateur",
  followUpCta: "Obtenir une relance d'examinateur",
  examinerInterviewTitle: "Entretien avec l'examinateur",
  examinerVoiceLabel: "Voix de l'examinateur",
  conversationSpeakerJury: 'Examinateur',
  conversationSpeakerStudent: 'Vous',
  transcriptPlaceholder: "La transcription du micro apparaît ici, vous pouvez la corriger avant l'envoi...",
  improvementAxes: "Axes d'amélioration",
  hero: {
    badge: 'Oral EAF',
    title: "Une simulation officielle pensée comme un cockpit d'entraînement, pas comme un outil brut.",
    body:
      'Tirage, préparation, passage puis bilan. Tout est réuni dans un seul espace pour te garder concentré sur la qualité de ta prise de parole, la précision des attendus officiels et les points à retravailler la séance suivante.',
    prepLabel: 'Préparation',
    passageLabel: 'Passage',
    gradingLabel: 'Barème',
    simulationPrepValue: '30 min',
    simulationPassageValue: '20 min',
    freeValue: 'Libre',
    gradingValue: '2 + 8 + 2 + 8',
  },
  capabilities: {
    eyebrow: 'État des capacités',
    body: 'Le cockpit indique les briques réellement disponibles avant et pendant la simulation.',
    sttLabel: 'Transcription vocale',
    ragLabel: 'Références RAG',
    llmLabel: 'Évaluation IA',
    available: 'Disponible',
    degraded: 'Mode dégradé',
  },
  wizardPhases: {
    TIRAGE: 'Tirage',
    PREP: "Prépa 30'",
    PASSAGE: "Passage 20'",
    BILAN: 'Bilan',
  },
  stepLabels: {
    LECTURE: 'Lecture /2',
    EXPLICATION: 'Explication /8',
    GRAMMAIRE: 'Grammaire /2',
    ENTRETIEN: 'Entretien /8',
  },
  stepGuidance: {
    LECTURE: {
      title: 'Lecture expressive',
      body: 'Soigne le débit, les ponctuations et les respirations. La note vient autant de la netteté que de la simple fluidité.',
    },
    EXPLICATION: {
      title: 'Explication linéaire',
      body: 'Reste sur une problématique claire, des mouvements lisibles et des procédés commentés plutôt que simplement listés.',
    },
    GRAMMAIRE: {
      title: 'Question de grammaire',
      body: 'Nomme précisément le fait de langue, rattache-le à la phrase, puis explique brièvement son effet.',
    },
    ENTRETIEN: {
      title: "Entretien avec l'examinateur",
      body: "Réponds nettement, repars de l'œuvre choisie et garde une logique de dialogue plutôt qu'une mini dissertation flottante.",
    },
  },
  launch: {
    eyebrow: 'Démarrage',
    title: "Tirage au sort de l'extrait",
    body:
      "Choisis ton œuvre et le niveau de contrainte. La plateforme tire l'extrait, la question de grammaire puis t'installe directement dans le rythme de l'épreuve.",
    simulationMode: 'Simulation examen',
    practiceMode: 'Entraînement libre',
    freeModeHint: 'Mode libre : les timers sont désactivés, tu peux prendre ton temps.',
    workLabel: 'Œuvre du programme',
    startCta: 'Tirer un extrait',
    upcomingEyebrow: 'Ce qui va suivre',
    upcomingItems: [
      'Préparation structurée de 30 minutes avec notes personnelles.',
      'Passage en quatre temps : lecture, explication, grammaire, entretien.',
      'Bilan final /20 avec conseil concret pour la prochaine séance.',
    ],
    premiumEyebrow: 'Usage premium',
    premiumBody:
      'Une bonne simulation orale ne cherche pas à parler beaucoup. Elle cherche à rendre la parole plus nette, plus articulée et plus défendable étape après étape.',
    premiumCta: 'Préparer cette œuvre avec le guidage',
  },
  prep: {
    eyebrow: 'Préparation',
    title: 'Préparation',
    body:
      'Lis, structure, choisis tes procédés et prépare la grammaire. Les notes restent un brouillon de travail, pas un objet évalué.',
    freeModeLabel: 'Mode libre',
    excerptLabel: 'Extrait tiré',
    grammarQuestionLabel: 'Question de grammaire :',
    targetSentenceLabel: 'Phrase cible :',
    chosenWorkLabel: 'Œuvre choisie (entretien) :',
    notesLabel: 'Notes de préparation (brouillon — non évaluées)',
    notesPlaceholder: 'Structure ton explication linéaire, prépare tes axes, note les procédés...',
    startPassageCta: 'Commencer le passage (20 min)',
    checklistTitle: 'Checklist de préparation',
    checklistCompletedSuffix: 'étapes complétées',
    checklist: [
      { id: 'contexte', label: "Identifier le contexte de l'extrait (auteur, œuvre, mouvement)" },
      { id: 'mouvement', label: "Repérer les mouvements du texte et l'articulation des parties" },
      { id: 'problematique', label: "Formuler une problématique d'analyse" },
      { id: 'procedes', label: 'Relever les procédés clés + citations à commenter' },
      { id: 'grammaire', label: 'Anticiper la question de grammaire (nature, fonction, analyse)' },
    ],
    reminderEyebrow: 'Rappel',
    reminderBody:
      'La préparation utile ne cherche pas à tout écrire. Elle cherche à sécuriser les mouvements du texte, deux ou trois procédés décisifs et une réponse propre à la grammaire.',
    reminderCta: 'Débloquer un point avant le passage',
  },
  passage: {
    noMicError: 'Le micro navigateur ou MediaRecorder ne sont pas disponibles. Saisis ta réponse en texte.',
    eyebrow: 'Passage oral',
    phaseSuffix: 'phase',
    freeModeLabel: 'Mode libre',
    detailsSummary: 'Extrait & question de grammaire',
    grammarLabel: 'Grammaire :',
    targetSentenceLabel: 'Phrase cible :',
    interviewOnLabel: 'Entretien sur :',
    recordPromptPrefix: 'Clique pour enregistrer —',
    recordingLabel: 'Enregistrement en cours...',
    transcriptLabel: 'Transcription / réponse',
    submitPrefix: 'Soumettre —',
    transcriptHint:
      "La transcription vocale utilise le service audio serveur quand il est disponible. En cas d'indisponibilité, saisis ta réponse en texte.",
    feedbackEyebrow: 'Feedbacks intermédiaires',
    strengthsLabel: 'Points forts',
    listenCta: 'Écouter',
    examinerFollowUpPrefix: "Relance de l'examinateur :",
    principleEyebrow: 'Principe de séance',
    principleBody:
      "Mieux vaut quatre prises de parole nettes avec un vrai retour intermédiaire qu'une longue réponse confuse. Le cockpit est conçu pour rendre cette discipline plus facile.",
    principleCta: 'Reprendre cette phase avec le guidage',
  },
  bilan: {
    officialEyebrow: 'Bilan officiel',
    globalEyebrow: 'Bilan global',
    finalAdviceEyebrow: 'Conseil final',
    restartCta: 'Nouvelle simulation',
    debriefCta: 'Débriefer cette simulation',
    badgePrefix: 'Badge débloqué :',
    phaseLabels: {
      lecture: 'Lecture',
      explication: 'Explication',
      grammaire: 'Grammaire',
      entretien: 'Entretien',
    },
  },
  worksProgram: [
    'Cahier de Douai — Arthur Rimbaud',
    "La rage de l'expression — Francis Ponge",
    'Mes forêts — Hélène Dorion',
    'Discours de la servitude volontaire — Étienne de La Boétie',
    'Entretiens sur la pluralité des mondes — Fontenelle',
    "Lettres d'une Péruvienne — Françoise de Graffigny",
    'Le Menteur — Pierre Corneille',
    "On ne badine pas avec l'amour — Alfred de Musset",
    'Pour un oui ou pour un non — Nathalie Sarraute',
    'Manon Lescaut — Abbé Prévost',
    'La Peau de chagrin — Honoré de Balzac',
    'Sido suivi de Les Vrilles de la vigne — Colette',
  ],
} as const;
